version: 2.1 # CircleCI configuration version
executors:
  java-executor:
    docker:
      - image: cimg/openjdk:11.0

jobs:
  build:
    executor: java-executor
    steps:
      - checkout # Checkout code from GitHub

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
            
      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # Compile and Test
      - run: mvn clean test

workflows:
  build_and_test:
    jobs:
      - build
